version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - unused

    # Security
    - gosec

    # Bug detection
    - bodyclose
    - nilerr
    - nilnil

    # Style
    - misspell
    - whitespace

    # Code complexity
    - gocyclo
    - gocognit
    - nestif

    # Code quality
    - gocritic
    - revive
    - unconvert
    - unparam
    - wastedassign
    - goconst
    - asciicheck
    - bidichk
    - durationcheck
    - usestdlibvars
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports

settings:
  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  nestif:
    min-complexity: 5

  misspell:
    locale: US

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
