# This file was generated by GoReleaser. DO NOT EDIT.
cask "timeotter" do
  name "timeotter"
  desc "Google Calendar to cron sync"
  homepage "https://github.com/bupd/timeotter"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "timeotter"

  on_macos do
    on_intel do
      url "https://github.com/bupd/timeotter/releases/download/v#{version}/timeotter_#{version}_darwin_amd64.tar.gz"
      sha256 "e2439198405021aa36e692347b2a3b17ac580ba6bab98f97ffef035ee940ec64"
    end
    on_arm do
      url "https://github.com/bupd/timeotter/releases/download/v#{version}/timeotter_#{version}_darwin_arm64.tar.gz"
      sha256 "3fd2a44ebc2b0a65dd1e0843af338619abc0178a5ac3747b50aeadbb2fb1762e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bupd/timeotter/releases/download/v#{version}/timeotter_#{version}_linux_amd64.tar.gz"
      sha256 "07112b22b608edb4063c5bbab89e4db124746c19f67b649b674595297bedb0c1"
    end
    on_arm do
      url "https://github.com/bupd/timeotter/releases/download/v#{version}/timeotter_#{version}_linux_arm64.tar.gz"
      sha256 "9ed98c4795f8a7544a4e625c12a4b94a9b8354d1f1de35b9dbc397cbb90014c2"
    end
  end

  # No zap stanza required
end
